name: CI - ToDo API

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENV: dev

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install bandit pre-commit pytest-cov
        
      - name: Run pre-commit hooks
        run: |
          source .venv/bin/activate
          pre-commit run --all-files
      - name: Validar formato con Black
        run: |
          source .venv/bin/activate
          black --check .

      - name: Linter con Flake8
        run: |
          source .venv/bin/activate
          flake8 .

      - name: Análisis de seguridad con Bandit
        run: |
          source .venv/bin/activate
          bandit -r app -x tests
      - name: Copiar archivo de entorno
        run: cp .env.dev .env
        
      - name: Correr pruebas
        run: |
          source .venv/bin/activate
          pytest -ra --disable-warnings

      - name: Reporte de cobertura
        run: |
          source .venv/bin/activate
          pytest --cov=app --cov-report=term-missing
